// app/layout.tsx
import { fontSans, fontThai } from '@/utils/fonts';
import clsx from "clsx";
import "@/styles/globals.css";
import { Providers } from "./providers";

const defaultUrl = process.env.VERCEL_URL
  ? `https://${process.env.VERCEL_URL}`
  : "http://localhost:3000";

export const metadata = {
  metadataBase: new URL(defaultUrl),
  title: "Magnita Dashboard",
  description: "Generated by Kanda Digital Company",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={clsx(fontSans.variable, fontThai.variable)} suppressHydrationWarning>
      <body className={clsx("antialiased", fontSans.variable, fontThai.variable)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}